/* eslint-disable max-lines */
import * as path from 'path';
import { DSL } from '../types';
import { WebPageGenerator } from '../';

const dsl = {
  pageKey: 'test',
  container: {
    name: 'universal',
    lib: 'universal',
    entry: 'vize-main-entry',
  },
  global: {
    layoutMode: 'stream',
    pageMode: 'multi',
    globalProps: {},
    globalStyle: {
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      border: { type: 'none', color: '#161616', width: 1 },
      background: { color: '#ffffff', image: '', size: 'auto', position: 'center top', repeat: 'repeat-y' },
    },
    metaInfo: { title: 'vize page', desc: '', duration: null, expiredJump: '' },
  },
  pageInstances: [
    {
      key: 2,
      name: 'new page',
      path: '2',
      isHome: true,
      componentInstances: [
        {
          key: 6,
          component: 'universal_button',
          lib: 'universal',
          data: { text: '按钮' },
          style: {},
          commonStyle: {
            size: { autoWidth: true, width: 200, autoHeight: true, height: 80 },
            transform: { rotate: 0, opacity: 1, scale: 1, radius: 0 },
            text: { color: '#161616', fontSize: 14, lineHeight: 20, textAlign: 'center', weight: 'normal' },
            border: { type: 'none', color: '#161616', width: 1 },
            background: { color: 'transparent', image: '', size: 'auto', position: 'center top', repeat: 'repeat-y' },
            margin: { top: 12, left: 0, bottom: 12, right: 0 },
            padding: { top: 0, left: 8, bottom: 0, right: 8 },
            zIndex: true,
            position: true,
          },
          wrapperStyle: {
            background: { color: 'transparent', image: '', size: 'auto', position: 'center top', repeat: 'repeat-y' },
          },
          events: [
            {
              key: 7,
              data: {},
              trigger: { type: 'component_universal_trigger', triggerName: '__vize_component_event_trigger_click' },
              target: { type: 'action', id: 'universal_alert', lib: 'universal' },
              events: [],
            },
          ],
        },
        {
          key: 7,
          component: 'universal_container',
          lib: 'universal',
          data: {},
          style: {},
          commonStyle: {
            size: { autoWidth: true, width: 200, autoHeight: true, height: 80 },
            transform: { rotate: 0, opacity: 1, scale: 1, radius: 0 },
            text: { color: '#161616', fontSize: 14, lineHeight: 20, textAlign: 'center', weight: 'normal' },
            border: { type: 'none', color: '#161616', width: 1 },
            background: { color: 'transparent', image: '', size: 'auto', position: 'center top', repeat: 'repeat-y' },
            margin: { top: 0, left: 'auto', bottom: 0, right: 'auto' },
            padding: { top: 0, left: 0, bottom: 0, right: 0 },
            zIndex: true,
            position: true,
          },
          wrapperStyle: {},
          events: [],
          children: [
            {
              key: 11,
              component: 'universal_button',
              lib: 'universal',
              data: { text: '按钮' },
              style: {},
              commonStyle: {
                size: { autoWidth: true, width: 200, autoHeight: true, height: 80 },
                transform: { rotate: 0, opacity: 1, scale: 1, radius: 0 },
                text: { color: '#161616', fontSize: 14, lineHeight: 20, textAlign: 'center', weight: 'normal' },
                border: { type: 'none', color: '#161616', width: 1 },
                background: {
                  color: 'transparent',
                  image: '',
                  size: 'auto',
                  position: 'center top',
                  repeat: 'repeat-y',
                },
                margin: { top: 12, left: 0, bottom: 12, right: 0 },
                padding: { top: 0, left: 8, bottom: 0, right: 8 },
                zIndex: true,
                position: true,
              },
              wrapperStyle: {
                background: {
                  color: 'transparent',
                  image: '',
                  size: 'auto',
                  position: 'center top',
                  repeat: 'repeat-y',
                },
              },
              events: [],
            },
            {
              key: 12,
              component: 'universal_text',
              lib: 'universal',
              data: { text: '输入文本内容...' },
              style: {},
              commonStyle: {
                size: { autoWidth: true, width: 200, autoHeight: true, height: 80 },
                transform: { rotate: 0, opacity: 1, scale: 1, radius: 0 },
                text: { color: '#161616', fontSize: 14, lineHeight: 20, textAlign: 'center', weight: 'normal' },
                border: { type: 'none', color: '#161616', width: 1 },
                background: {
                  color: 'transparent',
                  image: '',
                  size: 'auto',
                  position: 'center top',
                  repeat: 'repeat-y',
                },
                margin: { top: 12, left: 0, bottom: 12, right: 0 },
                padding: { top: 0, left: 8, bottom: 0, right: 8 },
                zIndex: true,
                position: true,
              },
              wrapperStyle: {},
              events: [],
            },
          ],
        },
        {
          key: 8,
          component: 'universal_containerwithtitle',
          lib: 'universal',
          data: {},
          style: {},
          commonStyle: {},
          wrapperStyle: {},
          events: [],
          children: [],
        },
        {
          key: 9,
          component: 'universal_image',
          lib: 'universal',
          data: { src: 'https://img.alicdn.com/tfs/TB1PibhR4D1gK0jSZFsXXbldVXa-512-416.png' },
          style: {},
          commonStyle: {
            size: { autoWidth: true, width: 200, autoHeight: true, height: 80 },
            transform: { rotate: 0, opacity: 1, scale: 1, radius: 0 },
            border: { type: 'none', color: '#161616', width: 1 },
            margin: { top: 0, left: 'auto', bottom: 0, right: 'auto' },
            padding: { top: 0, left: 0, bottom: 0, right: 0 },
            zIndex: true,
            position: true,
          },
          wrapperStyle: {
            background: { color: 'transparent', image: '', size: 'auto', position: 'center top', repeat: 'repeat-y' },
          },
          events: [],
          hotAreas: [],
        },
        {
          key: 10,
          component: 'universal_text',
          lib: 'universal',
          data: { text: '输入文本内容...' },
          style: {},
          commonStyle: {
            size: { autoWidth: true, width: 200, autoHeight: true, height: 80 },
            transform: { rotate: 0, opacity: 1, scale: 1, radius: 0 },
            text: { color: '#161616', fontSize: 14, lineHeight: 20, textAlign: 'center', weight: 'normal' },
            border: { type: 'none', color: '#161616', width: 1 },
            background: { color: 'transparent', image: '', size: 'auto', position: 'center top', repeat: 'repeat-y' },
            margin: { top: 12, left: 0, bottom: 12, right: 0 },
            padding: { top: 0, left: 8, bottom: 0, right: 8 },
            zIndex: true,
            position: true,
          },
          wrapperStyle: {},
          events: [],
        },
      ],
      pluginInstances: [
        { key: 3, plugin: 'universal_share', lib: 'universal', data: { wording: '分享完成' }, events: [] },
      ],
    },
  ],
  editInfo: { maxKeys: { page: 2, component: 12, 'hot-area': 1, plugin: 3, action: 7 } },
} as DSL;

const generator = new WebPageGenerator({
  dsl,
  libsPath: path.resolve(__dirname, './libs'),
  depsPath: path.resolve(__dirname, './deps'),
  targetPath: path.resolve(__dirname, './dist'),
});

generator.dist().then(console.log);
