export enum RichTextFormat {
  bold = 'bold',
  italic = 'italic',
  underline = 'underline',
  code = 'code',
  block_quote = 'block-quote',
  numbered_list = 'numbered-list',
  bulleted_list = 'bulleted-list',
  h1 = 'h1',
  h2 = 'h2',
  h3 = 'h3',
  h4 = 'h4',
  h5 = 'h5',
  h6 = 'h6',
}
